language: "node_js"
node_js:
  - "0.10"
  - "0.8"
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script: "phantomjs components/phantom-jasmine/run_jasmine_test.coffee test/run/jasmine_test.html"
